run_name: OLMo-1B-TEST-1205-1637
seed: 6198
dry_run: false

wandb:
  name: ${run_name}
  project: olmo-small
  group: docker

model:
  d_model: 2048 # 1024 # 2048
  n_heads: 16
  n_layers: 16
  mlp_ratio: 8
  weight_tying: true
  alibi: false
  rope: true
  flash_attention: True  # not available on AMD
  attention_dropout: 0.0
  attention_layer_norm: false
  multi_query_attention: false
  include_bias: false
  block_type: sequential
  layer_norm_type: default
  layer_norm_with_affine: false
  bias_for_layer_norm: false
  attention_layer_norm_with_affine: false
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 2048
  vocab_size: 50280
  embedding_size: 50304
  eos_token_id: 0 # 50279 # 0
  pad_token_id: 1
  init_device: cuda
  init_fn: mitchell

#compile: null  # causes instability on AMD GPUs
compile:
  fullgraph: false

optimizer:
  name: adamw
  learning_rate: 4.0e-4
  weight_decay: 0.1
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 10

scheduler:
  name: cosine_with_warmup
  t_warmup: 2000
  alpha_f: 0.1

tokenizer:
  identifier: tokenizers/allenai_eleuther-ai-gpt-neox-20b-pii-special.json # tokenizers/OLMo-1B-tokenizer.json
  truncate_direction: right

#save_folder: ${path.choose:${oc.env:SCRATCH_DIR,no_exist}/checkpoints,/results}/${oc.env:SLURM_JOB_ID,${run_name}}
save_folder: ${output_path}/${run_name}
save_overwrite: false
# Sharded checkpoints (best for restarts)
save_interval: 2000
save_num_checkpoints_to_keep: 9
# Unsharded checkpoints (for final storage)
save_interval_unsharded: 2000
save_num_unsharded_checkpoints_to_keep: -1

load_path: null

#max_duration: 739_328  # 3.1T tokens
max_duration: 1ep  # 3.1T tokens
global_train_batch_size: 2048
device_train_microbatch_size: 3

precision: amp_bf16
distributed_strategy: ddp
ddp:
  grad_sync_mode: batch
  find_unused_params: false
#fsdp:
#  wrapping_strategy: null
#  precision: mixed
#fsdp:
#  wrapping_strategy: by_block
#  precision: mixed

max_grad_norm: 1.0
max_grad_norm_ratio: null

speed_monitor:
  window_size: 20

eval_interval: ${save_interval}
eval_subset_num_batches: -1
device_eval_batch_size: ${device_train_microbatch_size}
evaluators:
  # lump all the small datasets together (we still get separate metrics).
  - label: v3-small-ppl-validation
    data:
      num_workers: 60
      drop_last: true
      datasets:
#        same_valid_dataset:
#          - ${input_path}/16_npy_gpt_uint16_all_0.08/Run_20241205-213909_27000_to_27500_01_00000.npy
        v3-small-c4_en-validation:
#          - https://olmo-data.org/eval-data/perplexity/v3_small_gptneox20b/c4_en/val/part-0-00000.npy
          - /${input_path}/11_gpt_v3_ppl_valid/c4_en_val_part-0-00000.npy
        v3-small-dolma_books-validation:
#          - https://olmo-data.org/eval-data/perplexity/v3_small_gptneox20b/dolma_books/val/part-0-00000.npy
          - /${input_path}/11_gpt_v3_ppl_valid/dolma_books_val_part-0-00000.npy
#        v3-small-dolma_common-crawl-validation:
##          - https://olmo-data.org/eval-data/perplexity/v3_small_gptneox20b/dolma_common-crawl/val/part-0-00000.npy
#          - /${input_path}/11_gpt_v3_ppl_valid/dolma_common-crawl_val_part-0-00000.npy
#        v3-small-dolma_pes2o-validation:
##          - https://olmo-data.org/eval-data/perplexity/v3_small_gptneox20b/dolma_pes2o/val/part-0-00000.npy
#          - /${input_path}/11_gpt_v3_ppl_valid/dolma_pes2o_val_part-0-00000.npy
#        v3-small-dolma_reddit-validation:
##          - https://olmo-data.org/eval-data/perplexity/v3_small_gptneox20b/dolma_reddit/val/part-0-00000.npy
#          - /${input_path}/11_gpt_v3_ppl_valid/dolma_reddit_val_part-0-00000.npy
#        v3-small-dolma_stack-validation:
##          - https://olmo-data.org/eval-data/perplexity/v3_small_gptneox20b/dolma_stack/val/part-0-00000.npy
#          - /${input_path}/11_gpt_v3_ppl_valid/dolma_stack_val_part-0-00000.npy
        v3-small-dolma_wiki-validation:
#          - https://olmo-data.org/eval-data/perplexity/v3_small_gptneox20b/dolma_wiki/val/part-0-00000.npy
          - /${input_path}/11_gpt_v3_ppl_valid/dolma_wiki_val_part-0-00000.npy

  - label: piqa
    type: downstream

  - label: hellaswag
    type: downstream

  - label: winogrande
    type: downstream

  - label: openbook_qa
    type: downstream

#  - label: boolq
#    type: downstream
#
#  - label: sciq
#    type: downstream
#
#  - label: arc_easy
#    type: downstream
#
#  - label: arc_challenge
#    type: downstream
#
#  - label: copa
#    type: downstream
#
#  - label: commonsense_qa
#    type: downstream
#
#  - label: social_iqa
#    type: downstream

#  - label: mmlu_stem_var
#    type: downstream
#
#  - label: mmlu_humanities_var
#    type: downstream
#
#  - label: mmlu_social_sciences_var
#    type: downstream
#
#  - label: mmlu_other_var
#    type: downstream
#
#  - label: mmlu_stem_mc_5shot
#    type: downstream
#
#  - label: mmlu_humanities_mc_5shot
#    type: downstream
#
#  - label: mmlu_social_sciences_mc_5shot
#    type: downstream
#
#  - label: mmlu_other_mc_5shot
#    type: downstream
#
#  - label: mmlu_stem_mc_5shot_test
#    type: downstream
#
#  - label: mmlu_humanities_mc_5shot_test
#    type: downstream
#
#  - label: mmlu_social_sciences_mc_5shot_test
#    type: downstream
#
#  - label: mmlu_other_mc_5shot_test
#    type: downstream
#
#  - label: basic_arithmetic
#    type: downstream
#
#  - label: trivia_qa_wiki_ppl
#    type: downstream
#
#  - label: natural_qs_open_ppl
#    type: downstream
#
#  - label: arc_easy_ppl
#    type: downstream
data:
  pad_direction: right
  num_workers: 60
  drop_last: true
  pin_memory: true
  prefetch_factor: 8 # 16
  persistent_workers: true
  timeout: 0
  paths:
#    - /home/lvbo/12_npy_gpt_uint16_0.1/Run_20241125-114153_0_to_2000_test_0_00000.npy
#    - /home/lvbo/13_npy_gpt_uint16_0.1/Run_20241125-114153_0_to_2000_test_0_00000.npy
#    - /home/lvbo/14_npy_gpt_uint16_0.07/Run_20241125-114153_0_to_2000_0_00000.npy
#    - /home/lvbo/14_npy_gpt_uint16_0.07/Run_20241125-114153_0_to_2000_2_00000.npy
#    - /home/lvbo/14_npy_gpt_uint16_0.07/Run_20241125-114153_0_to_2000_1_00000.npy
#    - /home/lvbo/14_npy_gpt_uint16_0.07/Run_20241125-114925_2000_to_4000_2_00000.npy
#    - /home/lvbo/14_npy_gpt_uint16_0.07/Run_20241125-114925_2000_to_4000_1_00000.npy
#    - /home/lvbo/14_npy_gpt_uint16_0.07/Run_20241125-114925_2000_to_4000_0_00000.npy
    ###########  48 G  start ########
    - ${input_path}/15_npy_gpt_uint16_all_0.15/26000-27000_ALL_03_00000.npy
    - ${input_path}/15_npy_gpt_uint16_all_0.15/26000-27000_ALL_10_00000.npy
    - ${input_path}/15_npy_gpt_uint16_all_0.15/26000-27000_ALL_14_00000.npy
    - ${input_path}/15_npy_gpt_uint16_all_0.15/26000-27000_ALL_11_00000.npy
    - ${input_path}/15_npy_gpt_uint16_all_0.15/26000-27000_ALL_16_00000.npy
    - ${input_path}/15_npy_gpt_uint16_all_0.15/26000-27000_ALL_12_00000.npy
    - ${input_path}/15_npy_gpt_uint16_all_0.15/26000-27000_ALL_18_00000.npy
    - ${input_path}/15_npy_gpt_uint16_all_0.15/26000-27000_ALL_02_00000.npy
    - ${input_path}/15_npy_gpt_uint16_all_0.15/26000-27000_ALL_00_00000.npy
    - ${input_path}/15_npy_gpt_uint16_all_0.15/26000-27000_ALL_04_00000.npy
    - ${input_path}/15_npy_gpt_uint16_all_0.15/26000-27000_ALL_19_00000.npy
    - ${input_path}/15_npy_gpt_uint16_all_0.15/26000-27000_ALL_20_00000.npy
    - ${input_path}/15_npy_gpt_uint16_all_0.15/26000-27000_ALL_06_00000.npy
    - ${input_path}/15_npy_gpt_uint16_all_0.15/26000-27000_ALL_13_00000.npy
    - ${input_path}/15_npy_gpt_uint16_all_0.15/26000-27000_ALL_05_00000.npy
    - ${input_path}/15_npy_gpt_uint16_all_0.15/26000-27000_ALL_01_00000.npy
    - ${input_path}/15_npy_gpt_uint16_all_0.15/26000-27000_ALL_15_00000.npy
    - ${input_path}/15_npy_gpt_uint16_all_0.15/26000-27000_ALL_08_00000.npy
    - ${input_path}/15_npy_gpt_uint16_all_0.15/26000-27000_ALL_09_00000.npy
    - ${input_path}/15_npy_gpt_uint16_all_0.15/26000-27000_ALL_07_00000.npy
    - ${input_path}/15_npy_gpt_uint16_all_0.15/26000-27000_ALL_17_00000.npy
    ###########  48G  end ########

    ###########  34G  start ########
    - ${input_path}/16_npy_gpt_uint16_all_0.08/Run_20241205-213909_27000_to_27500_12_00000.npy
    - ${input_path}/16_npy_gpt_uint16_all_0.08/Run_20241205-213909_27000_to_27500_10_00000.npy
    - ${input_path}/16_npy_gpt_uint16_all_0.08/Run_20241205-213909_27000_to_27500_13_00000.npy
    - ${input_path}/16_npy_gpt_uint16_all_0.08/Run_20241205-213909_27000_to_27500_00_00000.npy
    - ${input_path}/16_npy_gpt_uint16_all_0.08/Run_20241205-213909_27000_to_27500_04_00000.npy
    - ${input_path}/16_npy_gpt_uint16_all_0.08/Run_20241205-213909_27000_to_27500_08_00000.npy
    - ${input_path}/16_npy_gpt_uint16_all_0.08/Run_20241205-213909_27000_to_27500_03_00000.npy
    - ${input_path}/16_npy_gpt_uint16_all_0.08/Run_20241205-213909_27000_to_27500_09_00000.npy
    - ${input_path}/16_npy_gpt_uint16_all_0.08/Run_20241205-213909_27000_to_27500_06_00000.npy
    - ${input_path}/16_npy_gpt_uint16_all_0.08/Run_20241205-213909_27000_to_27500_14_00000.npy
    - ${input_path}/16_npy_gpt_uint16_all_0.08/Run_20241205-213909_27000_to_27500_02_00000.npy
    - ${input_path}/16_npy_gpt_uint16_all_0.08/Run_20241205-213909_27000_to_27500_07_00000.npy
    - ${input_path}/16_npy_gpt_uint16_all_0.08/Run_20241205-213909_27000_to_27500_11_00000.npy
    - ${input_path}/16_npy_gpt_uint16_all_0.08/Run_20241205-213909_27000_to_27500_05_00000.npy
    - ${input_path}/16_npy_gpt_uint16_all_0.08/Run_20241205-213909_27000_to_27500_01_00000.npy
    ###########  34G end ########

    ###########  51 G  start ########
    - ${input_path}/15_npy_gpt_uint16_0.06/Run_20241125-223448_6000_to_8000_1_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.06/Run_20241125-223437_4000_to_6000_0_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.06/Run_20241125-225207_10000_to_12000_0_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.06/Run_20241125-225207_10000_to_12000_3_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.06/Run_20241125-225207_10000_to_12000_1_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.06/Run_20241125-223437_4000_to_6000_1_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.06/Run_20241125-223448_6000_to_8000_2_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.06/Run_20241125-114925_2000_to_4000_1_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.06/Run_20241125-225347_12000_to_14000_1_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.06/Run_20241125-223448_6000_to_8000_0_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.06/Run_20241125-223437_4000_to_6000_3_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.06/Run_20241125-223448_6000_to_8000_3_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.06/Run_20241125-114153_0_to_2000_1_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.06/Run_20241125-114153_0_to_2000_0_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.06/Run_20241125-225207_10000_to_12000_2_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.06/Run_20241125-225347_12000_to_14000_2_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.06/Run_20241125-225347_12000_to_14000_3_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.06/Run_20241125-114925_2000_to_4000_0_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.06/Run_20241125-223437_4000_to_6000_2_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.06/Run_20241125-114925_2000_to_4000_2_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.06/Run_20241125-114925_2000_to_4000_3_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.06/Run_20241125-114153_0_to_2000_3_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.06/Run_20241125-225347_12000_to_14000_0_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.06/Run_20241125-114153_0_to_2000_2_00000.npy
        ###########  51 G  start ########
    ###########  57 G  start ########
    - ${input_path}/15_npy_gpt_uint16_0.04/Run_20241127-090831_20000_to_22000_1_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.04/Run_20241126-091826_14000_to_16000_3_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.04/Run_20241126-091826_14000_to_16000_2_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.04/Run_20241127-090807_18000_to_20000_2_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.04/Run_20241127-090831_20000_to_22000_4_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.04/Run_20241126-091852_16000_to_18000_0_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.04/Run_20241127-090852_22000_to_24000_1_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.04/Run_20241127-090807_18000_to_20000_4_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.04/Run_20241126-091826_14000_to_16000_0_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.04/Run_20241126-091852_16000_to_18000_2_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.04/Run_20241127-090807_18000_to_20000_0_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.04/Run_20241126-091852_16000_to_18000_4_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.04/Run_20241127-090807_18000_to_20000_3_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.04/Run_20241127-090831_20000_to_22000_0_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.04/Run_20241127-090852_22000_to_24000_3_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.04/Run_20241127-090852_22000_to_24000_4_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.04/Run_20241127-090831_20000_to_22000_2_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.04/Run_20241127-090807_18000_to_20000_1_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.04/Run_20241127-090852_22000_to_24000_0_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.04/Run_20241126-091826_14000_to_16000_4_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.04/Run_20241126-091852_16000_to_18000_3_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.04/Run_20241127-090852_22000_to_24000_2_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.04/Run_20241127-090831_20000_to_22000_3_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.04/Run_20241126-091826_14000_to_16000_1_00000.npy
    - ${input_path}/15_npy_gpt_uint16_0.04/Run_20241126-091852_16000_to_18000_1_00000.npy
    ###########  57 G  end ########
    ###########  12G  start ########
    - ${input_path}/17_npy_gpt_uint16_24000_26000_0.04/Run_20241127-090947_24000_to_26000_2_00000.npy
    - ${input_path}/17_npy_gpt_uint16_24000_26000_0.04/Run_20241127-090947_24000_to_26000_4_00000.npy
    - ${input_path}/17_npy_gpt_uint16_24000_26000_0.04/Run_20241127-090947_24000_to_26000_1_00000.npy
    - ${input_path}/17_npy_gpt_uint16_24000_26000_0.04/Run_20241127-090947_24000_to_26000_3_00000.npy
    - ${input_path}/17_npy_gpt_uint16_24000_26000_0.04/Run_20241127-090947_24000_to_26000_0_00000.npy
    ###########  12G end ########

#    - https://olmo-data.org/preprocessed/olmo-mix/v1_5/gpt-neox-20b-pii-special/part-000-00000.npy
#    - https://olmo-data.org/preprocessed/olmo-mix/v1_5/gpt-neox-20b-pii-special/part-000-00001.npy
