run_name: OLMo-120M-uint32_0_2000_common-test
seed: 6198
dry_run: false

wandb:
  name: ${run_name}
  project: olmo-tiny
  group: common

model:
  d_model: 512 # 256
  n_heads: 16 # 8
  n_layers: 16 #8
  mlp_ratio: 8
#  mlp_hidden_size: 22016
  weight_tying: false
  alibi: false
  rope: true
  flash_attention: true
  attention_dropout: 0.0
  attention_layer_norm: true
  #clip_qkv: null
  include_bias: false
  block_type: sequential
  layer_norm_type: rms
  layer_norm_with_affine: true
  layer_norm_eps: 1e-6
  bias_for_layer_norm: false
  attention_layer_norm_with_affine: false
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 4096
#  vocab_size: 50280
#  embedding_size: 50304
#  eos_token_id: 0
#  pad_token_id: 1
  vocab_size: 100278
  embedding_size: 100352
  eos_token_id: 100257
  pad_token_id: 100277
  init_device: cuda
  init_fn: normal
  init_std: 0.02
  init_cutoff_factor: 3
  norm_after: true

ddp:
  grad_sync_mode: batch
  find_unused_params: false

#compile: null
compile:
  fullgraph: false

optimizer:
  name: adamw
  learning_rate: 6.0e-4
  weight_decay: 0.1
  eps: 1e-8
  decay_norm_and_bias: true
  decay_embeddings: false
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 10

scheduler:
  name: cosine_with_warmup
  t_warmup: 5000
  alpha_f: 0.1
  warmup_min_lr: 0

tokenizer:
  identifier: tokenizers/allenai_dolma2.json   # allenai_gpt-neox-olmo-dolma-v1_5.json
#  identifier: tokenizers/allenai_gpt-neox-olmo-dolma-v1_5.json
  truncate_direction: right

save_folder: workspace/${run_name}  # doesn't matter since we'll upload to S3
#remote_save_folder: s3://ai2-llm/checkpoints/olmo-tiny/${run_name}
save_overwrite: True

# Unsharded checkpoints (for ddp)
save_interval_unsharded: 5000
save_num_unsharded_checkpoints_to_keep: -1

load_path: null

max_duration: 1ep
stop_at: 406_934
global_train_batch_size: 1024
device_train_microbatch_size: 4

precision: amp_bf16
distributed_strategy: ddp

gen1_gc_interval: 1

max_grad_norm: 1.0
max_grad_norm_ratio: null

speed_monitor:
  window_size: 20

eval_interval: 100
eval_subset_num_batches: -1
device_eval_batch_size: ${device_train_microbatch_size}
evaluators:
  - label: all-small-ppl-validation
    data:
      num_workers: 20
      drop_last: true
      memmap_dtype: uint32
      datasets:
#        c4_en-validation:
#          - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/c4_en/val/part-0-00000.npy
#        dolma_books-validation:
#          - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/dolma_books/val/part-0-00000.npy
#        dolma_common-crawl-validation:
#          - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/dolma_common-crawl/val/part-0-00000.npy
#        dolma_pes2o-validation:
#          - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/dolma_pes2o/val/part-0-00000.npy
#        dolma_reddit-validation:
#          - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/dolma_reddit/val/part-0-00000.npy
#        dolma_stack-validation:
#          - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/dolma_stack/val/part-0-00000.npy
#        dolma_wiki-validation:
#          - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/dolma_wiki/val/part-0-00000.npy
#        ice-validation:
#          - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/ice/val/part-0-00000.npy
#        m2d2_s2orc-validation:
#          - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/m2d2_s2orc/val/part-0-00000.npy
#        pile-validation:
#        - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/pile/val/part-0-00000.npy
#        wikitext_103-validation:
#          - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/wikitext_103/val/part-0-00000.npy
        c4_en-validation:
          - /home/lvbo/10_valid_data_dolma2/v3_small_gptneox20b_c4_en/part-0-00000.npy
        dolma_books-validation:
          - /home/lvbo/10_valid_data_dolma2/v3_small_gptneox20b_dolma_books/part-0-00000.npy
        dolma_common-crawl-validation:
          - /home/lvbo/10_valid_data_dolma2/v3_small_gptneox20b_dolma_common-crawl/part-0-00000.npy
        dolma_pes2o-validation:
          - /home/lvbo/10_valid_data_dolma2/v3_small_gptneox20b_dolma_pes2o/part-0-00000.npy
        dolma_reddit-validation:
          - /home/lvbo/10_valid_data_dolma2/v3_small_gptneox20b_dolma_reddit/part-0-00000.npy
        dolma_stack-validation:
          - /home/lvbo/10_valid_data_dolma2/v3_small_gptneox20b_dolma_stack/part-0-00000.npy
        dolma_wiki-validation:
          - /home/lvbo/10_valid_data_dolma2/v3_small_gptneox20b_dolma_wiki/part-0-00000.npy
        ice-validation:
          - /home/lvbo/10_valid_data_dolma2/v3_small_gptneox20b_ice/part-0-00000.npy
        m2d2_s2orc-validation:
          - /home/lvbo/10_valid_data_dolma2/v3_small_gptneox20b_m2d2_s2orc/part-0-00000.npy
        pile-validation:
          - /home/lvbo/10_valid_data_dolma2/v3_small_gptneox20b_pile/part-0-00000.npy
        wikitext_103-validation:
          - /home/lvbo/10_valid_data_dolma2/v3_small_gptneox20b_wikitext_103/part-0-00000.npy

  ##########################
  # Downstream evaluations #
  ##########################
  - label: piqa
    type: downstream

  - label: hellaswag
    type: downstream

  - label: winogrande
    type: downstream

  - label: openbook_qa
    type: downstream

  - label: sciq
    type: downstream

  - label: arc_easy
    type: downstream

  - label: commonsense_qa
    type: downstream

  - label: social_iqa
    type: downstream

  - label: mmlu_stem_var
    type: downstream

  - label: mmlu_humanities_var
    type: downstream

  - label: mmlu_social_sciences_var
    type: downstream

  - label: mmlu_other_var
    type: downstream

  - label: mmlu_stem_mc_5shot
    type: downstream

  - label: mmlu_humanities_mc_5shot
    type: downstream

#  - label: mmlu_social_sciences_mc_5shot
#    type: downstream
#
#  - label: mmlu_other_mc_5shot
#    type: downstream
#
#  - label: mmlu_stem_mc_5shot_test
#    type: downstream
#
#  - label: mmlu_humanities_mc_5shot_test
#    type: downstream
#
#  - label: mmlu_social_sciences_mc_5shot_test
#    type: downstream
#
#  - label: mmlu_other_mc_5shot_test
#    type: downstream

  - label: trivia_qa_wiki_ppl
    type: downstream

  - label: natural_qs_open_ppl
    type: downstream

  - label: arc_easy_ppl
    type: downstream

data:
  pad_direction: right
  num_workers: 20
  drop_last: true
  pin_memory: true
  prefetch_factor: 8
  persistent_workers: true
  memmap_dtype: uint32
  timeout: 0
  instance_filter:
    repetition_max_period: 13
    repetition_min_period: 1
    repetition_max_count: 32
  paths:
    ######### NON WEB DATA #########
    - /home/lvbo/06_npy_uint32_0.03/Run_20241125-114153_0_to_2000_0_00000.npy
#    - /home/lvbo/10_train_data_olmo_orin/dolma2/wiki/part-1-00000.npy   # olmo2  wiki  4B
#    - /home/lvbo/10_train_data_olmo_orin/dolma2/wiki/part-1-00000.npy   # olmo2  wiki  4B
#    - /home/lvbo/10_train_data_olmo_orin/part-000-00001.npy
#    - /home/lvbo/10_train_data_olmo_orin/part-004-00001.npy
    # all filter
#   - /home/lvbo/03_npy_data_dolma2/Run_20241125-114153_0_to_2000_0_00000.npy
#   - /home/lvbo/03_npy_data_dolma2/Run_20241125-114153_0_to_2000_0_00001.npy
#   - /home/lvbo/03_npy_data_dolma2/Run_20241125-114153_0_to_2000_0_00002.npy
#   - /home/lvbo/03_npy_data_dolma2/Run_20241125-114153_0_to_2000_0_00003.npy
#   - /home/lvbo/03_npy_data_dolma2/Run_20241125-114153_0_to_2000_0_00004.npy
#   - /home/lvbo/03_npy_data_dolma2/Run_20241125-114153_0_to_2000_1_00000.npy
#   - /home/lvbo/03_npy_data_dolma2/Run_20241125-114153_0_to_2000_1_00001.npy
#   - /home/lvbo/03_npy_data_dolma2/Run_20241125-114153_0_to_2000_1_00002.npy
#   - /home/lvbo/03_npy_data_dolma2/Run_20241125-114153_0_to_2000_1_00003.npy
#   - /home/lvbo/03_npy_data_dolma2/Run_20241125-114153_0_to_2000_1_00004.npy
#   - /home/lvbo/03_npy_data_dolma2/Run_20241125-114153_0_to_2000_2_00000.npy
#   - /home/lvbo/03_npy_data_dolma2/Run_20241125-114153_0_to_2000_2_00001.npy
#   - /home/lvbo/03_npy_data_dolma2/Run_20241125-114153_0_to_2000_2_00002.npy
#   - /home/lvbo/03_npy_data_dolma2/Run_20241125-114153_0_to_2000_2_00003.npy
#   - /home/lvbo/03_npy_data_dolma2/Run_20241125-114153_0_to_2000_2_00004.npy
#   - /home/lvbo/03_npy_data_dolma2/Run_20241125-114153_0_to_2000_3_00000.npy
#   - /home/lvbo/03_npy_data_dolma2/Run_20241125-114153_0_to_2000_3_00001.npy
     #  common
#   - /home/lvbo/05_npy_all_common/Run_20241125-114925_2000_to_4000_0_00000.npy
#   - /home/lvbo/05_npy_all_common/Run_20241125-114925_2000_to_4000_1_00000.npy
#   - /home/lvbo/05_npy_all_common/Run_20241125-114925_2000_to_4000_1_00001.npy
#   - /home/lvbo/05_npy_all_common/Run_20241125-223437_4000_to_6000_0_00000.npy
#   - /home/lvbo/05_npy_all_common/Run_20241125-223437_4000_to_6000_0_00001.npy
#   - /home/lvbo/05_npy_all_common/Run_20241125-223448_6000_to_8000_0_00000.npy
#   - /home/lvbo/05_npy_all_common/Run_20241125-223448_6000_to_8000_0_00001.npy
#   - /home/lvbo/05_npy_all_common/Run_20241125-225207_10000_to_12000_0_00000.npy
#   - /home/lvbo/05_npy_all_common/Run_20241125-225207_10000_to_12000_0_00001.npy
#   - /home/lvbo/05_npy_all_common/Run_20241125-225347_12000_to_14000_0_00000.npy
#   - /home/lvbo/05_npy_all_common/Run_20241125-225347_12000_to_14000_0_00001.npy
#   - /home/lvbo/05_npy_all_common/Run_20241126-091826_14000_to_16000_0_00000.npy
#   - /home/lvbo/05_npy_all_common/Run_20241126-091826_14000_to_16000_0_00001.npy
   # common

    # bjm
#   - /root/a100_nas_lvbo/peixunban/2011_bjm/dclm_pretrain_token_npy/base/07_00002.npy
#   - /root/a100_nas_lvbo/peixunban/2011_bjm/dclm_pretrain_token_npy/base/05_00001.npy
#   - /root/a100_nas_lvbo/peixunban/2011_bjm/dclm_pretrain_token_npy/base/01_00000.npy
#   - /root/a100_nas_lvbo/peixunban/2011_bjm/dclm_pretrain_token_npy/base/03_00000.npy
#   - /root/a100_nas_lvbo/peixunban/2011_bjm/dclm_pretrain_token_npy/base/03_00001.npy
#   - /root/a100_nas_lvbo/peixunban/2011_bjm/dclm_pretrain_token_npy/base/06_00002.npy
#   - /root/a100_nas_lvbo/peixunban/2011_bjm/dclm_pretrain_token_npy/base/03_00002.npy
#   - /root/a100_nas_lvbo/peixunban/2011_bjm/dclm_pretrain_token_npy/base/00_00002.npy
#   - /root/a100_nas_lvbo/peixunban/2011_bjm/dclm_pretrain_token_npy/base/08_00001.npy
#   - /root/a100_nas_lvbo/peixunban/2011_bjm/dclm_pretrain_token_npy/base/02_00002.npy
#   - /root/a100_nas_lvbo/peixunban/2011_bjm/dclm_pretrain_token_npy/base/00_00000.npy
#   - /root/a100_nas_lvbo/peixunban/2011_bjm/dclm_pretrain_token_npy/base/02_00001.npy
#   - /root/a100_nas_lvbo/peixunban/2011_bjm/dclm_pretrain_token_npy/base/08_00002.npy
#   - /root/a100_nas_lvbo/peixunban/2011_bjm/dclm_pretrain_token_npy/base/06_00000.npy
#   - /root/a100_nas_lvbo/peixunban/2011_bjm/dclm_pretrain_token_npy/base/09_00001.npy
#   - /root/a100_nas_lvbo/peixunban/2011_bjm/dclm_pretrain_token_npy/base/05_00000.npy
#   - /root/a100_nas_lvbo/peixunban/2011_bjm/dclm_pretrain_token_npy/base/07_00000.npy
#   - /root/a100_nas_lvbo/peixunban/2011_bjm/dclm_pretrain_token_npy/base/00_00001.npy
#   - /root/a100_nas_lvbo/peixunban/2011_bjm/dclm_pretrain_token_npy/base/07_00001.npy
#   - /root/a100_nas_lvbo/peixunban/2011_bjm/dclm_pretrain_token_npy/base/08_00000.npy
#   - /root/a100_nas_lvbo/peixunban/2011_bjm/dclm_pretrain_token_npy/base/04_00001.npy
#   - /root/a100_nas_lvbo/peixunban/2011_bjm/dclm_pretrain_token_npy/base/09_00000.npy
#   - /root/a100_nas_lvbo/peixunban/2011_bjm/dclm_pretrain_token_npy/base/02_00000.npy
#   - /root/a100_nas_lvbo/peixunban/2011_bjm/dclm_pretrain_token_npy/base/01_00002.npy
#   - /root/a100_nas_lvbo/peixunban/2011_bjm/dclm_pretrain_token_npy/base/04_00002.npy
#   - /root/a100_nas_lvbo/peixunban/2011_bjm/dclm_pretrain_token_npy/base/04_00000.npy
#   - /root/a100_nas_lvbo/peixunban/2011_bjm/dclm_pretrain_token_npy/base/09_00002.npy
#   - /root/a100_nas_lvbo/peixunban/2011_bjm/dclm_pretrain_token_npy/base/06_00001.npy
#   - /root/a100_nas_lvbo/peixunban/2011_bjm/dclm_pretrain_token_npy/base/01_00001.npy
#   - /root/a100_nas_lvbo/peixunban/2011_bjm/dclm_pretrain_token_npy/base/05_00002.npy
  ## bjm end


